BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Build" (
	"BuildId"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT,
	"GameVersion"	TEXT,
	PRIMARY KEY("BuildId")
);
CREATE TABLE IF NOT EXISTS "GuideStepCategory" (
	"CategoryId"	TEXT NOT NULL UNIQUE,
	"Text"	TEXT NOT NULL,
	PRIMARY KEY("CategoryId")
);
CREATE TABLE IF NOT EXISTS "Attribute" (
	"AttributeId"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "Gem" (
	"GemId"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Active"	INTEGER NOT NULL DEFAULT 1,
	"MaxLevel"	INTEGER,
	"GemLinkId"	INTEGER NOT NULL,
	"AttributeId"	INTEGER NOT NULL,
	FOREIGN KEY("GemLinkId") REFERENCES "GemLink"("GemLinkId"),
	FOREIGN KEY("AttributeId") REFERENCES "Attribute"("AttributeId"),
	PRIMARY KEY("GemId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GuideStepPoint" (
	"GuideStepPointId"	INTEGER NOT NULL UNIQUE,
	"Text"	TEXT NOT NULL,
	"ParentPoint"	INTEGER,
	"StepId"	INTEGER NOT NULL,
	"StepPointIndex"	INTEGER NOT NULL,
	FOREIGN KEY("StepId") REFERENCES "GuideStep"("GuideStepId"),
	PRIMARY KEY("GuideStepPointId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GuideStep" (
	"GuideStepId"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Category"	TEXT NOT NULL,
	"Act"	INTEGER NOT NULL,
	"ActStepIndex"	INTEGER NOT NULL,
	"BuildId"	TEXT NOT NULL,
	FOREIGN KEY("BuildId") REFERENCES "Build"("BuildId"),
	FOREIGN KEY("Category") REFERENCES "GuideStepCategory"("CategoryId"),
	PRIMARY KEY("GuideStepId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GemLink" (
	"GemLinkId"	INTEGER NOT NULL UNIQUE,
	"Act"	INTEGER NOT NULL,
	"BuildId"	TEXT NOT NULL,
	PRIMARY KEY("GemLinkId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TargetLevel" (
	"TargetLevelId"	INTEGER NOT NULL UNIQUE,
	"Act"	INTEGER NOT NULL,
	"BuildId"	TEXT NOT NULL,
	"Level"	TEXT NOT NULL,
	"Progress"	TEXT NOT NULL,
	FOREIGN KEY("BuildId") REFERENCES "Build"("BuildId"),
	PRIMARY KEY("TargetLevelId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ZoneMap" (
	"ZoneMapId"	INTEGER NOT NULL UNIQUE,
	"Act"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"FileName"	TEXT NOT NULL,
	"ZoneIndex"	INTEGER NOT NULL,
	PRIMARY KEY("ZoneMapId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "User" (
	"UserId"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT,
	"Salt"	TEXT,
	PRIMARY KEY("UserId" AUTOINCREMENT)
);
COMMIT;
