BEGIN TRANSACTION;
INSERT INTO "GuideStepCategory" VALUES ('QUEST','Quest');
INSERT INTO "GuideStepCategory" VALUES ('WAYPOINT','Waypoint');
INSERT INTO "GuideStepCategory" VALUES ('LEVEL','Level');
INSERT INTO "GuideStepCategory" VALUES ('CONTINUE','Continue');
INSERT INTO "GuideStepCategory" VALUES ('OVERVIEW','Overview');
INSERT INTO "GuideStepCategory" VALUES ('BEGINNING','Beginning');
INSERT INTO "GuideStepCategory" VALUES ('ZONE','Zone');
INSERT INTO "GuideStepCategory" VALUES ('GEM','Gem');
INSERT INTO "Attribute" VALUES ('STR','Strength');
INSERT INTO "Attribute" VALUES ('DEX','Dexterity');
INSERT INTO "Attribute" VALUES ('INT','Intelligence');
INSERT INTO "ZoneMap" VALUES (1,1,'The Coast','a1_coast',1);
INSERT INTO "ZoneMap" VALUES (2,1,'The Mud Flats','a1_mudflats',2);
INSERT INTO "ZoneMap" VALUES (3,1,'The Submerged Passage','a1_submergedpassage',3);
INSERT INTO "ZoneMap" VALUES (4,1,'The Flooded Depths','a1_floodeddepths',4);
INSERT INTO "ZoneMap" VALUES (5,1,'The Climb','a1_climb',5);
INSERT INTO "ZoneMap" VALUES (6,1,'The Lower Prison','a1_lowerprison',6);
INSERT INTO "ZoneMap" VALUES (7,1,'The Upper Prison','a1_upperprison',7);
INSERT INTO "ZoneMap" VALUES (8,1,'The Prisoner''s Gate','a1_prisonersgate',8);
INSERT INTO "ZoneMap" VALUES (9,1,'The Ship Graveyard','a1_shipgraveyard',9);
INSERT INTO "ZoneMap" VALUES (10,1,'The Cavern of Wrath','a1_cavernofwrath',10);
INSERT INTO "ZoneMap" VALUES (11,1,'The Cavern of Anger','a1_cavernofanger',11);
INSERT INTO "ZoneMap" VALUES (12,2,'The Chamber of Sins 1','a2_chamberofsins1',1);
INSERT INTO "ZoneMap" VALUES (13,2,'The Chamber of Sins 2','a2_chamberofsins2',2);
INSERT INTO "ZoneMap" VALUES (14,2,'The Weaver''s Chambers','a2_weaverschambers',3);
INSERT INTO "ZoneMap" VALUES (15,2,'The Wetlands','a2_wetlands',4);
INSERT INTO "ZoneMap" VALUES (16,2,'The Vaal Ruins','a2_vaalruins',5);
INSERT INTO "ZoneMap" VALUES (17,2,'The Caverns','a2_caverns',6);
INSERT INTO "ZoneMap" VALUES (30,3,'The Slums','a3_slums',1);
INSERT INTO "ZoneMap" VALUES (31,3,'The Crematorium','a3_crematorium',2);
INSERT INTO "ZoneMap" VALUES (32,3,'The Sewers','a3_sewers',3);
INSERT INTO "ZoneMap" VALUES (33,3,'The Marketplace','a3_marketplace',4);
INSERT INTO "ZoneMap" VALUES (34,3,'The Battlefront','a3_battlefront',5);
INSERT INTO "ZoneMap" VALUES (35,3,'The Docks','a3_docks',6);
INSERT INTO "ZoneMap" VALUES (36,3,'The Solaris Temple 1','a3_solaristemple1',7);
INSERT INTO "ZoneMap" VALUES (37,3,'The Solaris Temple 2','a3_solaristemple2',8);
INSERT INTO "ZoneMap" VALUES (38,3,'The Ebony Barracks','a3_ebonybarracks',9);
INSERT INTO "ZoneMap" VALUES (39,3,'The Lunaris Temple 1','a3_lunaristemple1',10);
INSERT INTO "ZoneMap" VALUES (40,3,'The Lunaris Temple 2','a3_lunaristemple2',11);
INSERT INTO "ZoneMap" VALUES (41,3,'The Imperial Gardens','a3_imperialgardens',12);
INSERT INTO "ZoneMap" VALUES (42,4,'The Dried Lake','a4_driedlake',1);
INSERT INTO "ZoneMap" VALUES (43,4,'The Mines 1','a4_mines1',2);
INSERT INTO "ZoneMap" VALUES (44,4,'The Mines 2','a4_mines2',3);
INSERT INTO "ZoneMap" VALUES (45,4,'The Crystal Veins','a4_crystalveins',4);
INSERT INTO "ZoneMap" VALUES (46,4,'Kaom''s Dream','a4_kaomsdream',5);
INSERT INTO "ZoneMap" VALUES (47,4,'Kaom''s Stronghold','a4_kaomsstronghold',6);
INSERT INTO "ZoneMap" VALUES (48,4,'The Belly of the Beast 1','a4_bellyofthebeast1',7);
INSERT INTO "ZoneMap" VALUES (49,4,'The Belly of the Beast 2','a4_bellyofthebeast2',8);
INSERT INTO "ZoneMap" VALUES (50,4,'The Harvest','a4_harvest',9);
INSERT INTO "ZoneMap" VALUES (51,4,'The Ascent','a4_ascent',10);
INSERT INTO "ZoneMap" VALUES (52,5,'The Slave Pens','a5_slavepens',1);
INSERT INTO "ZoneMap" VALUES (53,5,'The Control Blocks','a5_controlblocks',2);
INSERT INTO "ZoneMap" VALUES (54,5,'Oriath Square','a5_oriathsquare',3);
INSERT INTO "ZoneMap" VALUES (55,5,'The Templar Courts','a5_templarcourts',4);
INSERT INTO "ZoneMap" VALUES (56,5,'Chamber of Innocence','a5_chamberofinnocence',5);
INSERT INTO "ZoneMap" VALUES (57,5,'The Torched Courts','a5_torchedcourts',6);
INSERT INTO "ZoneMap" VALUES (58,5,'The Ruined Square','a5_ruinesquare',7);
INSERT INTO "ZoneMap" VALUES (59,5,'The Ossuary','a5_ossuary',8);
INSERT INTO "ZoneMap" VALUES (60,5,'The Reliquary','a5_reliquary',9);
INSERT INTO "ZoneMap" VALUES (61,6,'The Coast','a6_coast',1);
INSERT INTO "ZoneMap" VALUES (62,6,'The Mud Flats','a6_mudflats',2);
INSERT INTO "ZoneMap" VALUES (63,6,'The Karui Fortress','a6_karuifortress',3);
INSERT INTO "ZoneMap" VALUES (64,6,'The Ridge','a6_ridge',4);
INSERT INTO "ZoneMap" VALUES (65,6,'The Lower Prison','a6_lowerprison',5);
INSERT INTO "ZoneMap" VALUES (66,6,'Prisoner''s Gate','a6_prisonersgate',6);
INSERT INTO "ZoneMap" VALUES (67,6,'The Riverways','a6_riverways',7);
INSERT INTO "ZoneMap" VALUES (68,6,'The Cavern of Anger','a6_cavernofanger',8);
INSERT INTO "ZoneMap" VALUES (69,6,'The Brine King’s Reef','a6_brinekingsreef',9);
INSERT INTO "ZoneMap" VALUES (70,7,'The Crossroads','a7_crossroads',1);
INSERT INTO "ZoneMap" VALUES (71,7,'The Crypt 1','a7_crypt1',2);
INSERT INTO "ZoneMap" VALUES (72,7,'The Crypt 2','a7_crypt2',3);
INSERT INTO "ZoneMap" VALUES (73,7,'The Chamber of Sins 1','a7_chamberofsins1',4);
INSERT INTO "ZoneMap" VALUES (74,7,'The Chamber of Sins 2','a7_chamberofsins2',5);
INSERT INTO "ZoneMap" VALUES (75,7,'The Den','a7_den',6);
INSERT INTO "ZoneMap" VALUES (76,7,'The Vaal City','a7_vaalcity',7);
INSERT INTO "ZoneMap" VALUES (77,8,'The Toxic Conduits','a8_toxicconduits1',1);
INSERT INTO "ZoneMap" VALUES (78,8,'Doedre’s Cesspool','a8_doedrescesspool',2);
INSERT INTO "ZoneMap" VALUES (79,8,'The Toxic Conduits (Waypoint)','a8_toxicconduits2',3);
INSERT INTO "ZoneMap" VALUES (80,8,'The Quay','a8_quay',4);
INSERT INTO "ZoneMap" VALUES (81,8,'The Grain Gate','a8_graingate',5);
INSERT INTO "ZoneMap" VALUES (82,8,'Solaris Temple 1','a8_solaristemple1',6);
INSERT INTO "ZoneMap" VALUES (83,8,'Solaris Temple 2','a8_solaristemple2',7);
INSERT INTO "ZoneMap" VALUES (84,8,'The Bath House','a8_bathhouse',8);
INSERT INTO "ZoneMap" VALUES (85,8,'The Lunaris Concourse','a8_lunarisconcourse',9);
INSERT INTO "ZoneMap" VALUES (86,8,'The Lunaris Temple 1','a8_lunaristemple1',10);
INSERT INTO "ZoneMap" VALUES (87,8,'The Lunaris Temple 2','a8_lunaristemple2',11);
INSERT INTO "ZoneMap" VALUES (88,9,'The Descent','a9_descent',1);
INSERT INTO "ZoneMap" VALUES (89,9,'The Vastiri Desert','a9_vastiridesert',2);
INSERT INTO "ZoneMap" VALUES (90,9,'The Oasis','a9_oasis',3);
INSERT INTO "ZoneMap" VALUES (91,9,'The Foothills','a9_foothills',4);
INSERT INTO "ZoneMap" VALUES (92,9,'The Tunnel','a9_tunnel',5);
INSERT INTO "ZoneMap" VALUES (93,9,'The Quarry','a9_quarry',6);
INSERT INTO "ZoneMap" VALUES (94,9,'The Refinery','a9_refinery',7);
INSERT INTO "ZoneMap" VALUES (95,9,'The Belly of the Beast','a9_bellyofthebeast',8);
INSERT INTO "ZoneMap" VALUES (96,10,'The Ravaged Square','a10_ravagedsquare',1);
INSERT INTO "User" VALUES (1,'test','''24??&??:??????7O?|??6d?#?j?s?0Q@2??OI???n?T?w?B??YZ??&?;m?*y???P?;?zH>?R???x???j? ????s????????"?L???\? ????Y?"SH?[?','bazqux');
INSERT INTO "User" VALUES (3,'admin','qQQgrYBTQ7QLLuzl+WiVkfciL6Sj6wTV2rMJtky9fs8nSEVghTxPp3/TvjSgKKI4ImrtAt/4coic3TP4+aMhohgD5ontxMPJEG7ak1nGKJu6lD2Zl0XA9xQ9hw90y1BQ454FweYcB7ZlAvoGCxE8G18mbc/Di2NK9pEUCVR1CQDOplBktSS7LrVIjpgYaYVK2qTPFM/y/5vJFigzMC6Oa0o6rCpeCgry0jRzZUS0DIKQpzIH7iwgf6uFxZYyef5iKWcenYwG3r+xk6ZrF7Ory8kfIUQgBLaEU02JVjpXKe+d+CMe374DJ4e1TBWkzFhMpCZGkrt1GYTfafDhUMqJ6PvZPR5P2EgF8HoyBDC8o0qNFbFhh0SzA3+FEwV8Z27BiyF6EROYIYQA71QtLstCcgF//MZkz6ET9UBKYuPRmbwt0yfh2WLBZSmH8lZCDszSPHOeGim6z4nTcV11CuSizOk2/BNHyqzVBrNE84vhAkC4D3exGmrNOGfKPiLi405ti3sfkeVEgD9lbDmScvD7UDuvqqcrZLdeeN81zYT/R5SJ9JeYlg4q8WXvXY/QIvTMLTmmOtYvgpFVe6Iv4pecaBJQ1j//HPbM+aKckvnUNwRgxlDf/m6vjtU31jeWi6FQI4ImYE6G5iUEY8J7uCWSmvkzZl4Vn/pTlexi8YjiQNw=','dNBa831LZo+SoAALSiCQv3P11M6BwopFRPsl328XgqY=');
COMMIT;
